<?php

namespace EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AbontnewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbontnewsRepository extends EntityRepository
{
    public function findEmail($emailverif)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a.anlEmail FROM EcommerceBundle:Abontnews a WHERE a.anlEmail = :email')
            ->setParameters('email', $emailverif)
            ->getResult();
    }
}
