<?php

namespace EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdresseModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseModeleRepository extends EntityRepository
{

    public function getAdresses4Commande($id_com)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM EcommerceBundle:AdresseModele p 
                            WHERE (p.adrIdcom = :idCom)')
            ->setParameter('idCom', $id_com)
            ->getResult();
    }
}
