<?php

namespace EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    //
    //  Catégories de produit par Libellé d'administration
    //
    public function getCategorieByLibAdmin()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p 
                            FROM EcommerceBundle:Categorie p 
                            ORDER BY p.catLibAdmin ASC')
            ->getResult();
    }
}
