<?php

namespace EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CatlibRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatlibRepository extends EntityRepository
{

    public function getLibellesCat($id_cat)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p.ctlCateg, p.ctlType, p.ctlItem FROM EcommerceBundle:Catlib p 
                            WHERE (p.ctlIdcat = :idCat AND p.ctlLocale = :locale)')
            ->setParameter('idCat', $id_cat)
            ->setParameter('locale', "fr")
            ->getResult();
    }

}
