<?php

namespace EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompdtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompdtRepository extends EntityRepository
{
    public function getProdts4Commande($id_comm)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p, a FROM EcommerceBundle:Compdt p JOIN p.cxpIdpdt a
                            WHERE (p.cxpIdcom = :idComm)')
            ->setParameter('idComm', $id_comm)
            ->getResult();
    }

}
