<?php

namespace EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangRepository extends EntityRepository
{

    public function getLangByCode($Lng_Code)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM EcommerceBundle:Lang p
                            WHERE (p.lngCode = :CodeLng)')
            ->setParameter('CodeLng', $Lng_Code)
            ->getResult();
    }

    public function getLangActives()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM EcommerceBundle:Lang p
                            WHERE (p.lngEtat = :Etat OR p.lngCode = :CodeLng)')
            ->setParameter('Etat', true)
            ->setParameter('CodeLng', "fr")
            ->getResult();
    }

}
