<?php

namespace EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParamlibRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamlibRepository extends EntityRepository
{
    public function getParamlib4ParamLang($id_param, $langue)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.prlIdprm = :idParam')
            ->setParameter('idParam', $id_param)
            ->andWhere('c.prlLocale = :lang')
            ->setParameter('lang', $langue)
        ;
        return $qb->getQuery()->getResult();
    }
}
