<?php

namespace site\BagueBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BagueRepository extends EntityRepository
{
}
